window:
  dynamic_title: true
  dimensions:
    columns: 0
    lines: 0

  position:
    x: 50
    y: 50

  padding:
    x: 35
    y: 35 

  dynamic_padding: false
  decorations: none

scrolling:
  history: 50000
  multiplier: 3

font:
  normal:
    family: Fira Code
    style: Regular

  bold:
    family: Fira Code
    style: Bold

  italic:
    family: Fira Code
    style: Bold Italic

  size: 13.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

colors:

  primary:
    background: '#2c2c2c'
    foreground: '#d6d6d6'

    dim_foreground:    '#dbdbdb'
    bright_foreground: '#d9d9d9'
    dim_background:    '#202020'
    bright_background: '#3a3a3a'

  cursor:
    text:   '#2c2c2c'
    cursor: '#d9d9d9'

  normal:
    black:   '#1c1c1c'
    red:     '#bc5653'
    green:   '#909d63'
    yellow:  '#ebc17a'
    blue:    '#7eaac7'
    magenta: '#aa6292'
    cyan:    '#86d3ce'
    white:   '#cacaca'

  bright:
    black:   '#636363'
    red:     '#bc5653'
    green:   '#909d63'
    yellow:  '#ebc17a'
    blue:    '#7eaac7'
    magenta: '#aa6292'
    cyan:    '#86d3ce'
    white:   '#f7f7f7'

  dim:
    black:   '#232323'
    red:     '#74423f'
    green:   '#5e6547'
    yellow:  '#8b7653'
    blue:    '#556b79'
    magenta: '#6e4962'
    cyan:    '#5c8482'
    white:   '#828282'

background_opacity: 0.8

key_bindings:
    - { key: J,        mods: Alt,           chars: 'j'                       }
    - { key: K,        mods: Alt,           chars: 'k'                       }
    - { key: H,        mods: Alt,           chars: 'h'                       }
    - { key: L,        mods: Alt,           chars: 'l'                       }
    - { key: T,        mods: Alt,           chars: 't'                       }
    - { key: W,        mods: Alt|Shift,     chars: 'W'                       }
    - { key: P,        mods: Alt,           chars: 'p'                       }
    - { key: N,        mods: Alt,           chars: 'n'                       }
    - { key: D,        mods: Alt,           chars: 'd'                       }
    - { key: E,        mods: Alt,           chars: 'e'                       }
    - { key: X,        mods: Alt|Shift,     chars: 'X'                       }

